import { useMemo, useState } from 'react'
import { SkuTrendChart } from '../../components/SkuTrendChart'
import { filterSkuOrders, summarizeOrderGeography, type GeographyLevel, type OrderGeographySummary, type OrderProfitSummary, type SkuOrderFilterSpec, type SkuProfitSummary } from '../../core/analytics/orderProfit'
import type { AdvertisingSkuInsight } from '../../core/analytics/advertisingSummary'
import { useScrollSelectedDetail } from '../../components/useScrollDetailIntoView'

type Props = { readonly insight: AdvertisingSkuInsight; readonly product: SkuProfitSummary; readonly formatMoney: (value: number) => string; readonly onClose: () => void }
type GeographyMetric = 'SALES' | 'PROFIT' | 'EASY_SHIP' | 'RETURNS'
type DetailTab = 'OVERVIEW' | 'GEOGRAPHY' | 'ORDERS'

function MetricCards({ items }: { readonly items: readonly (readonly [string, string, string])[] }) {
  return <div className="sku-metric-grid">{items.map(([label, value, tone]) => <article className={`sku-mini-metric ${tone}`} key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
}

function GeographyAnalysis({ items, level, metric, formatMoney, onLevelChange, onMetricChange }: { readonly items: readonly OrderGeographySummary[]; readonly level: GeographyLevel; readonly metric: GeographyMetric; readonly formatMoney: (value: number) => string; readonly onLevelChange: (value: GeographyLevel) => void; readonly onMetricChange: (value: GeographyMetric) => void }) {
  const value = (item: OrderGeographySummary) => metric === 'PROFIT' ? Math.abs(item.profit) : metric === 'EASY_SHIP' ? Math.abs(item.easyShipFees) : metric === 'RETURNS' ? item.returnQuantity : item.grossSales
  const max = Math.max(1, ...items.map(value)), top = items.slice(0, 10)
  return <section className="sku-geography"><div className="geo-controls"><div className="product-mode"><button className={level === 'STATE' ? 'active' : ''} onClick={() => onLevelChange('STATE')}>State</button><button className={level === 'CITY' ? 'active' : ''} onClick={() => onLevelChange('CITY')}>City</button></div><select value={metric} onChange={(event) => onMetricChange(event.target.value as GeographyMetric)}><option value="SALES">Gross sales</option><option value="PROFIT">Profit</option><option value="EASY_SHIP">Easy Ship fees</option><option value="RETURNS">RTO vs customer returns</option></select></div>
    <div className="geo-layout"><div className="geo-chart">{top.map((item) => <div className="geo-row" key={item.location}><span title={item.location}>{item.location}</span><div className="geo-track">{metric === 'RETURNS' ? <><i className="geo-rto" style={{ width: `${item.rtoQuantity / max * 100}%` }} /><i className="geo-customer" style={{ width: `${item.customerReturnQuantity / max * 100}%` }} /><i className="geo-unknown" style={{ width: `${item.unknownReturnQuantity / max * 100}%` }} /></> : <i className={metric === 'PROFIT' && item.profit < 0 ? 'geo-negative' : `geo-${metric.toLowerCase()}`} style={{ width: `${value(item) / max * 100}%` }} />}</div><strong className={metric === 'PROFIT' ? item.profit >= 0 ? 'good-text' : 'bad-text' : ''}>{metric === 'RETURNS' ? item.returnQuantity : formatMoney(metric === 'PROFIT' ? item.profit : value(item))}</strong></div>)}{!top.length ? <p className="empty-state">No geographical data is available.</p> : null}{metric === 'RETURNS' ? <div className="geo-legend"><span className="rto">RTO</span><span className="customer">Customer return</span><span className="unknown">Unknown</span></div> : null}</div>
      <div className="table-scroll geo-table"><table><thead><tr><th>{level === 'STATE' ? 'State' : 'City'}</th><th>Orders</th><th>Sales</th><th>Profit</th><th>Margin</th><th>Easy Ship</th><th>RTO</th><th>Customer</th><th>Return rate</th></tr></thead><tbody>{items.map((item) => <tr key={item.location}><td><strong>{item.location}</strong></td><td>{item.orderCount}</td><td>{formatMoney(item.grossSales)}</td><td className={item.profit >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(item.profit)}</td><td>{item.profitMargin.toFixed(2)}%</td><td>{formatMoney(item.easyShipFees)}</td><td>{item.rtoQuantity}</td><td>{item.customerReturnQuantity}</td><td>{item.returnRate.toFixed(2)}%</td></tr>)}</tbody></table></div></div></section>
}

function OrderAudit({ order, formatMoney, onClose }: { readonly order: OrderProfitSummary; readonly formatMoney: (value: number) => string; readonly onClose: () => void }) {
  const rows: readonly (readonly [string, number])[] = [['Gross sales', order.grossSales], ['Refunds', -order.refunds], ['Marketplace charges', -order.marketplaceCharges], ['Easy Ship', -order.shippingFees], ['COGS', -order.netCogs], ['Reimbursements', order.reimbursements]]
  return <div className="inline-order-audit"><button className="close inline-close" onClick={onClose} aria-label="Close order audit">×</button><div className="order-detail"><div className="order-detail-title"><div><small>Selected order</small><h3>{order.orderId}</h3><p>{[order.city, order.state].filter(Boolean).join(', ') || 'Location unavailable'}</p></div><strong className={order.profit >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(order.profit)}</strong></div><div className="profit-components">{rows.map(([label, value]) => <div key={label}><span>{label}</span><strong className={value < 0 ? 'bad-text' : 'good-text'}>{formatMoney(value)}</strong></div>)}</div><details className="event-audit"><summary>{order.events.length} source-linked financial events</summary><div className="table-scroll"><table><thead><tr><th>Event</th><th>Money type</th><th>Raw label</th><th>Amount</th></tr></thead><tbody>{order.events.map((event) => <tr key={event.id}><td>{event.event}</td><td>{event.amountType}</td><td>{event.rawType || event.rawDescription || '—'}</td><td className={event.amount >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(event.amount)}</td></tr>)}</tbody></table></div></details></div></div>
}

export function AdvertisingSkuDrilldown({ insight, product, formatMoney, onClose }: Props) {
  const [tab, setTab] = useState<DetailTab>('OVERVIEW')
  const [status, setStatus] = useState(''), [returnType, setReturnType] = useState<NonNullable<SkuOrderFilterSpec['returnType']>>('ALL')
  const [accountType, setAccountType] = useState(''), [fulfillmentType, setFulfillmentType] = useState('')
  const [transactionCategory, setTransactionCategory] = useState<NonNullable<SkuOrderFilterSpec['transactionCategory']>>('ALL')
  const [geographyLevel, setGeographyLevel] = useState<GeographyLevel>('STATE'), [geographyMetric, setGeographyMetric] = useState<GeographyMetric>('SALES')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  useScrollSelectedDetail(selectedId, '.ad-sku-drilldown .inline-order-audit')
  const orders = useMemo(() => filterSkuOrders(product.orders, { status: status || undefined, returnType, accountType: accountType || undefined, fulfillmentType: fulfillmentType || undefined, transactionCategory }), [product.orders, status, returnType, accountType, fulfillmentType, transactionCategory])
  const geography = useMemo(() => summarizeOrderGeography(product.orders, geographyLevel), [product.orders, geographyLevel])
  const selected = orders.find((order) => order.orderId === selectedId) ?? null
  const values = (field: 'status' | 'accountType' | 'fulfillmentType') => [...new Set(product.orders.flatMap((order) => order[field] ? [order[field] as string] : []))].sort()
  const hasFilters = Boolean(status || accountType || fulfillmentType || returnType !== 'ALL' || transactionCategory !== 'ALL')
  const clear = () => { setStatus(''); setReturnType('ALL'); setAccountType(''); setFulfillmentType(''); setTransactionCategory('ALL'); setSelectedId(null) }
  const primary = [['Gross sales', formatMoney(product.grossSales), 'positive'], ['Direct ads', insight.hasDirectAttribution ? formatMoney(insight.directAdsSpend) : 'Unavailable', 'accent'], ['TACOS', insight.tacos === null ? 'Unavailable' : `${insight.tacos.toFixed(2)}%`, insight.tacos !== null && insight.tacos <= insight.breakEvenTacos ? 'positive' : 'neutral'], ['Profit before ads', formatMoney(insight.profitBeforeAds), insight.profitBeforeAds >= 0 ? 'positive' : 'negative']] as const
  const secondary = [['ROAS', insight.roas === null ? 'Unavailable' : `${insight.roas.toFixed(2)}×`, 'accent'], ['Profit after direct ads', insight.profitAfterDirectAds === null ? 'Unavailable' : formatMoney(insight.profitAfterDirectAds), insight.profitAfterDirectAds !== null && insight.profitAfterDirectAds >= 0 ? 'positive' : 'neutral'], ['Break-even TACOS', `${insight.breakEvenTacos.toFixed(2)}%`, 'neutral'], ['Maximum affordable ads', formatMoney(insight.maximumAffordableAds), 'neutral']] as const

  return <div className="drilldown-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="order-drilldown sku-mode ad-sku-drilldown" role="dialog" aria-modal="true" aria-label="SKU advertising analysis">
    <header className="drilldown-head"><div><small>SKU advertising analysis</small><h2>{product.sku}</h2><p>{product.orders.length.toLocaleString('en-IN')} linked orders · Current report filters applied</p></div><button className="close" onClick={onClose} aria-label="Close">×</button></header>
    <nav className="sku-detail-tabs" aria-label="SKU analysis sections">{([['OVERVIEW','Overview'],['GEOGRAPHY','Geography'],['ORDERS','Orders']] as const).map(([value,label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}{value === 'ORDERS' ? <small>{product.orders.length}</small> : null}</button>)}</nav>
    <div className="sku-drilldown-content">
      {tab === 'OVERVIEW' ? <><MetricCards items={primary} /><details className="sku-more-details"><summary>More advertising metrics <span>ROAS and break-even</span></summary><MetricCards items={secondary} /></details><aside className="ad-attribution-note"><span>i</span><div><strong>{insight.hasDirectAttribution ? `${formatMoney(insight.directAdsSpend)} directly attributed` : 'SKU advertising is unavailable'}</strong><p>{insight.hasDirectAttribution ? 'Only advertising transactions explicitly carrying this SKU are included. Unassigned report advertising is not spread across products.' : 'The settlement report does not identify which product consumed the advertising. This SKU therefore shows profit before ads; unassigned ads remain included only in overall business profit.'}</p></div></aside>{insight.hasDirectAttribution ? <div className="sku-visual-grid"><SkuTrendChart data={product.trend} formatMoney={formatMoney} /><section className="sku-cost-card"><div className="sku-chart-head"><div><small>Advertising headroom</small><h3>Direct spend vs break-even</h3></div></div><div className="ad-headroom"><div><span>Direct spend</span><strong>{formatMoney(insight.directAdsSpend)}</strong></div><div><span>Maximum affordable</span><strong>{formatMoney(insight.maximumAffordableAds)}</strong></div><i><b style={{ width: `${Math.min(100, insight.maximumAffordableAds ? insight.directAdsSpend / insight.maximumAffordableAds * 100 : 100)}%` }} /></i><p>{insight.profitAfterDirectAds !== null && insight.profitAfterDirectAds >= 0 ? `${formatMoney(insight.profitAfterDirectAds)} remains after directly attributed ads.` : `${formatMoney(Math.abs(insight.profitAfterDirectAds ?? 0))} beyond break-even.`}</p></div></section></div> : <SkuTrendChart data={product.trend} formatMoney={formatMoney} />}</> : null}
      {tab === 'GEOGRAPHY' ? <><div className="tab-intro"><div><small>Location analysis</small><h3>Where this SKU performs</h3></div><p>Compare demand, profitability, delivery cost and return behaviour by state or city.</p></div><GeographyAnalysis items={geography} level={geographyLevel} metric={geographyMetric} formatMoney={formatMoney} onLevelChange={setGeographyLevel} onMetricChange={setGeographyMetric} /></> : null}
      {tab === 'ORDERS' ? <section className="sku-orders tab-orders"><div className="tab-intro"><div><small>Order audit</small><h3>Inspect individual transactions</h3></div><p>These filters affect only the order table below.</p></div><div className="sku-order-filters"><select aria-label="Order status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{values('status').map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Return type" value={returnType} onChange={(event) => setReturnType(event.target.value as typeof returnType)}><option value="ALL">All return types</option><option value="RTO">RTO</option><option value="CUSTOMER_RETURN">Customer return</option><option value="UNKNOWN">Unknown return</option></select><select aria-label="Account type" value={accountType} onChange={(event) => setAccountType(event.target.value)}><option value="">All account types</option>{values('accountType').map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Fulfillment type" value={fulfillmentType} onChange={(event) => setFulfillmentType(event.target.value)}><option value="">All fulfillment types</option>{values('fulfillmentType').map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Transaction category" value={transactionCategory} onChange={(event) => setTransactionCategory(event.target.value as typeof transactionCategory)}><option value="ALL">All activity</option><option value="SALE">Sales</option><option value="REFUND">Refunds</option><option value="FEE">Fees</option><option value="REIMBURSEMENT">Reimbursements</option></select>{hasFilters ? <button className="secondary" onClick={clear}>Clear</button> : null}</div><div className="order-result-count">{orders.length.toLocaleString('en-IN')} of {product.orders.length.toLocaleString('en-IN')} orders</div><div className="sku-order-table table-scroll"><table><thead><tr><th>Order</th><th>Date</th><th>Location</th><th>Account</th><th>Fulfillment</th><th>Return</th><th>Sales</th><th>Profit</th></tr></thead><tbody>{orders.map((order) => <tr key={order.orderId} className="clickable-order" onClick={() => setSelectedId(order.orderId)}><td><strong>{order.orderId}</strong></td><td>{order.date ?? '—'}</td><td>{[order.city, order.state].filter(Boolean).join(', ') || '—'}</td><td>{order.accountType ?? '—'}</td><td>{order.fulfillmentType ?? '—'}</td><td>{order.returnType === 'CUSTOMER_RETURN' ? 'Customer return' : order.returnType ?? '—'}</td><td>{formatMoney(order.grossSales)}</td><td className={order.profit >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(order.profit)}</td></tr>)}{!orders.length ? <tr><td colSpan={8} className="empty-state">No orders match these filters.</td></tr> : null}</tbody></table></div>{selected ? <OrderAudit order={selected} formatMoney={formatMoney} onClose={() => setSelectedId(null)} /> : null}</section> : null}
    </div>
  </section></div>
}
