import { useState } from 'react'
import type { FeeAuditResult } from '../../core/analytics/feeAudit'
import type { OrderProfitSummary } from '../../core/analytics/orderProfit'
import { InlineOrderDetail } from '../../components/InlineOrderDetail'

type Props = { readonly result: FeeAuditResult; readonly orders: readonly OrderProfitSummary[]; readonly formatMoney: (value: number) => string; readonly onClose: () => void }

export function FeeAuditPanel({ result, orders, formatMoney, onClose }: Props) {
  const [selectedSku, setSelectedSku] = useState<string | null>(null)
  const [selectedOrder, setSelectedOrder] = useState<string | null>(null)
  const sku = result.skus.find(item => item.sku === selectedSku)
  const visibleOrders = sku ? sku.orderIds.flatMap(id => orders.find(order => order.orderId === id) ? [orders.find(order => order.orderId === id)!] : []) : []
  const maxCount = Math.max(1, ...result.distribution.map(item => item.count))
  return <div className="drilldown-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="metric-sku-drilldown fee-audit-panel" role="dialog" aria-modal="true" aria-label="Marketplace fee audit">
    <header className="drilldown-head"><div><button className="workspace-back" onClick={selectedSku ? () => { setSelectedSku(null); setSelectedOrder(null) } : onClose}>← {selectedSku ? 'Fee audit' : 'Dashboard'}</button><div className="workspace-breadcrumb"><span>Dashboard</span><b>/</b><span>Fee audit</span>{selectedSku ? <><b>/</b><strong>{selectedSku}</strong></> : null}</div><h2>{selectedSku ?? 'Marketplace fee audit'}</h2><p>{selectedSku ? 'Flagged fee patterns and affected orders for this SKU.' : 'Find unusual marketplace and shipping charges, then trace them to their source transactions.'}</p></div><button className="close desktop-workspace-close" onClick={onClose}>×</button></header>
    <div className="fee-audit-body">{!selectedSku ? <>
      <section className="fee-audit-kpis"><article><span>Warnings found</span><strong>{result.issueCount}</strong><small>{result.criticalCount} critical</small></article><article><span>Affected orders</span><strong>{result.affectedOrderCount}</strong><small>{result.affectedSkuCount} SKUs</small></article><article><span>Charges on flagged orders</span><strong>{formatMoney(result.flaggedCharges)}</strong><small>This is exposure, not automatically recoverable leakage</small></article><article><span>Fee rate</span><strong>{result.currentFeeRate.toFixed(2)}%</strong><small>{result.feeRateChange === null ? 'Previous period unavailable' : `${result.feeRateChange >= 0 ? '+' : ''}${result.feeRateChange.toFixed(2)} points vs previous`}</small></article></section>
      <section className="fee-audit-grid"><article className="panel"><div className="section-label"><span>Issue distribution</span><small>Warnings by rule</small></div><div className="fee-issue-bars">{result.distribution.length ? result.distribution.map(item => <div key={item.kind}><span>{item.label}</span><i><b style={{ width: `${item.count / maxCount * 100}%` }} /></i><strong>{item.count}</strong><small>{formatMoney(item.amount)}</small></div>) : <p className="empty-state">No fee anomalies were found in this period.</p>}</div></article><article className="panel fee-rule-note"><div className="section-label"><span>How warnings work</span><small>Deterministic checks</small></div><p>High fee share uses a visible 35% review threshold. Duplicate charges require matching type, raw label, amount, and posted time. Commission changes compare an order with the SKU median only when at least three observations exist.</p><p>A missing shipping reversal is shown as an audit warning. It does not automatically classify the return as RTO.</p></article></section>
      <section className="panel"><div className="section-label"><span>Affected SKUs</span><small>Select a SKU to inspect its orders</small></div><div className="table-scroll"><table className="fee-sku-table"><thead><tr><th>SKU</th><th>Warnings</th><th>Affected orders</th><th>Gross sales</th><th>Charges</th><th>Fee share</th></tr></thead><tbody>{result.skus.map(item => <tr className="clickable-order" key={item.sku} onClick={() => setSelectedSku(item.sku)}><td><strong>{item.sku}</strong></td><td>{item.issueCount}</td><td>{item.orderIds.length}</td><td>{formatMoney(item.grossSales)}</td><td>{formatMoney(item.flaggedCharges)}</td><td className={item.feeShare >= 35 ? 'bad-text' : ''}>{item.feeShare.toFixed(2)}%</td></tr>)}{!result.skus.length ? <tr><td colSpan={6}>No SKUs require fee review.</td></tr> : null}</tbody></table></div></section>
    </> : <>
      <section className="fee-audit-kpis"><article><span>SKU warnings</span><strong>{sku?.issueCount ?? 0}</strong></article><article><span>Affected orders</span><strong>{sku?.orderIds.length ?? 0}</strong></article><article><span>Charges</span><strong>{formatMoney(sku?.flaggedCharges ?? 0)}</strong></article><article><span>Fee share</span><strong>{(sku?.feeShare ?? 0).toFixed(2)}%</strong></article></section>
      <section className="panel"><div className="section-label"><span>Flagged orders</span><small>Select an order for its complete source-event audit</small></div><div className="fee-order-list">{visibleOrders.map(order => {
        const orderIssues = result.issues.filter(issue => issue.orderId === order.orderId && issue.skus.includes(selectedSku))
        const expanded = selectedOrder === order.orderId
        return <div className="fee-order-item" key={order.orderId}><button onClick={() => setSelectedOrder(expanded ? null : order.orderId)}><span><strong>{order.orderId}</strong><small>{order.date ?? 'Date unavailable'} · {order.city ?? 'Unknown city'}, {order.state ?? 'Unknown state'}</small></span><span className="fee-order-tags">{orderIssues.map(issue => <i className={issue.severity.toLowerCase()} key={issue.id}>{issue.label}</i>)}</span><b>{formatMoney(order.marketplaceCharges + order.shippingFees + order.advertising)}</b></button>{expanded ? <InlineOrderDetail order={order} formatMoney={formatMoney} onCollapse={() => setSelectedOrder(null)} /> : null}</div>
      })}</div></section>
    </>}</div>
  </section></div>
}
