import { useState } from 'react'
import type { DataQualityCenterResult, QualityAction } from '../../core/validation/dataQualityCenter'

type Props = { readonly result: DataQualityCenterResult; readonly formatMoney: (value: number) => string; readonly onAction: (action: Exclude<QualityAction, null>) => void }

const actionLabel: Record<Exclude<QualityAction, null>, string> = {
  REVIEW_CLASSIFICATION: 'Classify transactions', MANAGE_COSTS: 'Add product costs', COMPARE_REPORTS: 'Compare reports', REVIEW_EVENTS: 'Inspect records',
}

export function DataQualityCenter({ result, formatMoney, onAction }: Props) {
  const [showEvidence, setShowEvidence] = useState(false)
  const act = (action: Exclude<QualityAction, null>) => action === 'REVIEW_EVENTS' ? setShowEvidence(true) : onAction(action)
  return <section className={`quality-center ${result.overall.toLowerCase()}`} aria-labelledby="quality-center-title">
    <div className="section-heading"><div><small>Trust center</small><h2 id="quality-center-title">Report checks and reconciliation</h2></div><p>See what is reliable, what affects profit, and what needs your attention before making decisions.</p></div>
    <div className="quality-hero"><span>{result.overall === 'GOOD' ? '✓' : result.overall === 'CRITICAL' ? '!' : 'i'}</span><div><small>Overall report status</small><strong>{result.overall === 'GOOD' ? 'All checks passed' : result.overall === 'CRITICAL' ? 'A critical accuracy issue needs attention' : `${result.attentionCount} checks need attention`}</strong><p>Unknown values stay included and visible; settlement transfers remain outside operating profit.</p></div></div>
    <div className="quality-check-grid">{result.checks.map(check => <article className={`quality-check ${check.severity.toLowerCase()}`} key={check.id}><header><span>{check.severity === 'GOOD' ? '✓' : '!'}</span><div><small>{check.label}</small><strong>{check.id === 'reconciliation' && check.value.startsWith('Difference ') ? `Difference ${formatMoney(Number(check.value.slice(11)))}` : check.value}</strong></div></header><p>{check.explanation}</p>{check.action ? <button className="text-btn" onClick={() => check.action && act(check.action)}>{actionLabel[check.action]} →</button> : <small className="check-complete">No action required</small>}</article>)}</div>
    <div className="quality-detail-grid"><article><span>Sales missing costs</span><strong>{formatMoney(result.missingCostSales)}</strong><small>{result.missingCostOrders} affected orders · {result.missingCostSkus.length} SKUs</small></article><article><span>Unassigned advertising</span><strong>{formatMoney(result.unassignedAdvertising)}</strong><small>Included in business profit, not allocated to SKUs</small></article><article><span>Unassigned marketplace charges</span><strong>{formatMoney(result.unassignedMarketplaceCharges)}</strong><small>Global charges without SKU or order attribution</small></article><article><span>Release status</span><strong>{result.deferredEvents.toLocaleString('en-IN')} deferred</strong><small>{result.releasedEvents.toLocaleString('en-IN')} released · {result.otherStatusEvents.toLocaleString('en-IN')} other</small></article></div>
    {result.overlaps.length ? <details className="quality-overlaps"><summary>Saved reports with matching activity</summary><div>{result.overlaps.map(item => <div key={item.importId}><span><strong>{item.fileName}</strong><small>{item.matchingEvents.toLocaleString('en-IN')} matching transactions</small></span><b>{item.coveragePercent.toFixed(1)}%</b></div>)}</div></details> : null}
    {result.missingCostSkus.length ? <details className="quality-overlaps"><summary>SKUs missing product costs ({result.missingCostSkus.length})</summary><div className="missing-sku-list">{result.missingCostSkus.map(sku => <code key={sku}>{sku}</code>)}</div></details> : null}
    <div className="quality-evidence-head"><div><strong>Affected records</strong><small>{result.evidence.length.toLocaleString('en-IN')} evidence entries across all checks</small></div><button className="secondary" onClick={() => setShowEvidence(value => !value)}>{showEvidence ? 'Hide records' : 'Inspect records'}</button></div>
    {showEvidence ? <div className="quality-evidence-list">{result.evidence.length ? result.evidence.slice(0, 250).map((item, index) => <article key={`${item.id}:${item.reason}:${index}`}><span className="evidence-reason">{item.reason}</span><div><strong>{item.label}</strong><small>{item.orderId ?? 'No order ID'} · {item.sku ?? 'No SKU'} · {item.date ?? 'No date'}</small></div><b className={item.amount < 0 ? 'bad-text' : 'good-text'}>{formatMoney(item.amount)}</b></article>) : <p className="empty-state">No affected records were found.</p>}{result.evidence.length > 250 ? <p className="metric-note">Showing the first 250 evidence entries. All events remain preserved in the normalized report.</p> : null}</div> : null}
  </section>
}
