import { useMemo } from 'react'
import type { OrderProfitSummary } from '../core/analytics/orderProfit'
import { buildOrderAudit } from '../core/analytics/orderAudit'
import { orderTimeDimensions } from '../core/analytics/timeAnalysis'
import '../styles/inlineOrderDetail.css'
import { useScrollDetailIntoView } from './useScrollDetailIntoView'

type Props = { readonly order: OrderProfitSummary; readonly formatMoney: (value: number) => string; readonly onCollapse: () => void }

export function InlineOrderDetail({ order, formatMoney, onCollapse }: Props) {
  const detailRef = useScrollDetailIntoView<HTMLDivElement>(order.orderId)
  const audit = useMemo(() => buildOrderAudit(order), [order])
  const timing = useMemo(() => orderTimeDimensions(order), [order])
  const bridgeMax = Math.max(1, ...audit.bridge.map(item => Math.abs(item.value)))
  return <div className="inline-order-detail" ref={detailRef} onClick={event => event.stopPropagation()}>
    <header><div><span>Order explanation</span><strong>{order.orderId}</strong><small>{timing ? `${timing.date} · ${timing.time} · ${timing.weekday} · ${timing.week}` : order.date ?? 'Date unavailable'}</small></div><button onClick={onCollapse}>Collapse ↑</button></header>
    <div className="inline-order-summary"><div><span>SKU</span><strong>{order.skus.join(', ') || '—'}</strong></div><div><span>Location</span><strong>{[order.city, order.state].filter(Boolean).join(', ') || '—'}</strong></div><div><span>Payment</span><strong>{order.accountType ?? '—'}</strong></div><div><span>Fulfilment</span><strong>{order.fulfillmentType ?? '—'}</strong></div><div><span>Sold / returned</span><strong>{order.soldQuantity} / {order.returnQuantity}</strong></div><div><span>Return type</span><strong>{order.returnType === 'CUSTOMER_RETURN' ? 'Customer return' : order.returnType ?? 'Not returned'}</strong></div><div><span>Profit / delivered unit</span><strong>{order.profitPerDeliveredUnit === null ? 'Unavailable' : formatMoney(order.profitPerDeliveredUnit)}</strong></div><div><span>Break-even TACOS</span><strong>{order.breakEvenTacos === null ? 'Unavailable' : `${order.breakEvenTacos.toFixed(2)}%`}</strong></div></div>
    {order.returnQuantity > 0 ? <section className="inline-return-explanation"><div><span>Return classification</span><strong>{order.returnType === 'CUSTOMER_RETURN' ? 'Customer return' : order.returnType ?? 'Unknown'}</strong></div><p>{order.returnEvidence ?? 'No classification evidence is available.'}</p><small>Returned goods are treated as resellable; COGS is recovered according to the configured return policy.</small></section> : null}
    {order.costApplications?.length ? <section className="inline-cost-evidence"><div className="section-label"><span>Applied product costs</span><small>Cost record selected from the sale date</small></div>{order.costApplications.map(item => <div key={item.eventId}><span><strong>{item.sku}</strong><small>{item.costDate ? `Effective from ${item.costDate}` : 'Default fallback cost'} · {item.quantity} unit{item.quantity === 1 ? '' : 's'}</small></span><b>{formatMoney(item.unitCost)} / unit</b><em className={item.cogs < 0 ? 'good-text' : ''}>{formatMoney(item.cogs)}</em></div>)}</section> : null}
    {audit.warnings.length ? <div className="inline-order-warnings">{audit.warnings.map(warning => <span key={warning}>⚠ {warning}</span>)}</div> : null}
    <div className="inline-order-grid"><section><div className="section-label"><span>Profit breakdown</span><small>How this order becomes profit</small></div><div className="inline-profit-bridge">{audit.bridge.map(item => <div className={item.kind.toLowerCase()} key={item.id}><span>{item.label}</span><i><b style={{ width: `${Math.abs(item.value) / bridgeMax * 100}%` }} /></i><strong className={item.value < 0 ? 'bad-text' : item.kind === 'RESULT' ? 'good-text' : ''}>{formatMoney(item.value)}</strong></div>)}</div></section><section><div className="section-label"><span>Fee audit</span><small>Order-associated deductions and reversals</small></div><div className="inline-fee-grid">{audit.feeGroups.length ? audit.feeGroups.map(item => <div key={item.label}><span>{item.label}</span><strong>{formatMoney(item.value)}</strong></div>) : <p>No order-level fees found.</p>}</div></section></div>
    <section className="inline-timeline"><div className="section-label"><span>Transaction timeline</span><small>Running balance includes operating events only</small></div><div className="table-scroll"><table><thead><tr><th>Posted date/time</th><th>Source label</th><th>Classification</th><th>Amount</th><th>Running balance</th></tr></thead><tbody>{audit.timeline.map(item => <tr key={item.id}><td>{item.date ?? '—'}</td><td>{item.rawLabel}</td><td>{item.event} · {item.amountType}{!item.classified ? <small className="bad-text">Needs review</small> : null}</td><td className={item.amount < 0 ? 'bad-text' : 'good-text'}>{formatMoney(item.amount)}</td><td>{formatMoney(item.runningBalance)}</td></tr>)}</tbody></table></div></section>
  </div>
}
