import { useMemo, useState } from 'react'
import type React from 'react'
import type { MetricDrilldownResult } from '../core/analytics/metricDrilldown'
import type { TimePeriodPreset } from '../core/analytics/timePeriods'
import type { SkuProfitSummary } from '../core/analytics/orderProfit'
import type { SkuAdvertisingSummary } from '../core/analytics/advertisingSummary'
import { buildSkuWorkspace } from '../core/analytics/skuWorkspace'
import { SkuGeographyPanel } from './SkuGeographyPanel'
import { SkuOrderInvestigation } from './SkuOrderInvestigation'
import { SkuCommercialOverview } from './SkuCommercialOverview'
import '../styles/actionBoard.css'

type Props = { result: MetricDrilldownResult; products: readonly SkuProfitSummary[]; previousProducts: readonly SkuProfitSummary[]; advertisingSkus: readonly SkuAdvertisingSummary[]; comparisonPeriod: TimePeriodPreset | 'CUSTOM' | ''; initialSku?: string; formatMoney: (value: number) => string; onClose: () => void }
const percent = (value: number) => `${value.toFixed(2)}%`

export function MetricSkuDrilldown({ result, products, previousProducts, advertisingSkus, comparisonPeriod, initialSku, formatMoney, onClose }: Props) {
  const [sku, setSku] = useState<string | null>(initialSku ?? null)
  const [search, setSearch] = useState('')
  const [rankDirection, setRankDirection] = useState<'TOP' | 'BOTTOM'>('TOP')
  const [hideZero, setHideZero] = useState(false)
  const product = products.find(item => item.sku === sku)
  const previousProduct = previousProducts.find(item => item.sku === sku)
  const rows = result.rows.filter(row => row.label.toLowerCase().includes(search.trim().toLowerCase()) && (!hideZero || Math.abs(row.value ?? 0) >= .01)).sort((a, b) => rankDirection === 'TOP' ? Math.abs(b.value ?? 0) - Math.abs(a.value ?? 0) : Math.abs(a.value ?? 0) - Math.abs(b.value ?? 0))
  const workspace = useMemo(() => product ? buildSkuWorkspace(product, advertisingSkus.find(item => item.sku === product.sku)) : null, [product, advertisingSkus])
  const value = (amount: number | null) => amount === null ? '—' : result.format === 'MONEY' ? formatMoney(amount) : result.format === 'PERCENT' ? percent(amount) : amount.toLocaleString('en-IN')
  const trendValues = result.trend.map(point => point.value), trendMin = Math.min(0, ...trendValues), trendMax = Math.max(1, ...trendValues), trendRange = trendMax - trendMin || 1
  const trendPoints = result.trend.map((point, index) => `${20 + index * 560 / Math.max(1, result.trend.length - 1)},${150 - (point.value - trendMin) / trendRange * 125}`).join(' ')
  const geoMax = Math.max(1, ...result.geography.map(point => Math.abs(point.value)))
  const selectedPeriodId = comparisonPeriod || result.recommendedPeriod
  const comparison = result.periodComparisons.find(item => item.id === selectedPeriodId) ?? result.periodComparisons[0]

  return <div className="drilldown-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="metric-sku-drilldown" role="dialog" aria-modal="true">
    <header className="drilldown-head"><div>{product ? <button className="workspace-back" onClick={() => setSku(null)}>← {result.label}</button> : <button className="workspace-back" onClick={onClose}>← Dashboard</button>}<div className="workspace-breadcrumb"><span>Dashboard</span><b>/</b><span>{result.label}</span>{product ? <><b>/</b><strong>{product.sku}</strong></> : null}</div><h2>{product?.sku ?? `${result.label} by SKU`}</h2><p>{product ? 'Complete performance for this SKU in the current dashboard filters.' : `${value(result.total)} total · click any SKU for its complete overview.`}</p></div><button className="close desktop-workspace-close" onClick={onClose}>×</button></header>
    {!product ? <div className="metric-ranking">
      <section className="metric-overview"><div className="section-label"><span>{result.label} overview</span><small>Current dashboard filters</small></div><div className="metric-overview-grid">
        <article><span>Total {result.label}</span><strong>{value(result.total)}</strong></article>
        <article><span>SKUs with activity</span><strong>{result.overview.activeSkuCount.toLocaleString('en-IN')}</strong><small>of {result.overview.skuCount.toLocaleString('en-IN')} SKUs</small></article>
        <article><span>Leading SKU</span><strong title={result.overview.topSku ?? ''}>{result.overview.topSku ?? '—'}</strong><small>{value(result.overview.topSkuValue)}</small></article>
        <article className={result.additive && Math.abs(result.overview.unassignedAmount) >= .01 ? 'warning' : ''}><span>{result.additive ? 'Unassigned amount' : 'Metric type'}</span><strong>{result.additive ? value(result.overview.unassignedAmount) : 'Non-additive'}</strong><small>{result.additive ? 'Preserved separately' : 'Each SKU is calculated separately'}</small></article>
      </div></section>
      <section className="metric-visual-grid"><article className="metric-sku-chart"><div className="section-label"><span>Time trend</span><small>Daily movement</small></div>{result.trend.length ? <><svg viewBox="0 0 600 170" role="img" aria-label={`${result.label} time trend`}><line x1="20" y1="150" x2="580" y2="150" /><polyline points={trendPoints} /></svg><div className="trend-axis"><span>{result.trend[0]?.period}</span><span>{result.trend.at(-1)?.period}</span></div></> : <p className="empty-state">No dated activity.</p>}</article><article className="metric-sku-chart period-card"><div className="section-label"><span>Period comparison</span><small>{comparison?.label ?? 'Unavailable for this report'}</small></div>{comparison ? <><p className="period-explanation">Change the comparison period from the global report filters above the dashboard.</p><div className="period-compare"><div><span>Previous period</span><small>{comparison.previousLabel}</small><strong>{value(comparison.previousValue)}</strong></div><b>→</b><div><span>{comparison.label}</span><small>{comparison.currentLabel}</small><strong>{value(comparison.currentValue)}</strong></div></div><p className={(comparison.changePercent ?? 0) < 0 ? 'bad-text' : 'good-text'}>{comparison.changePercent === null ? 'Change unavailable because the previous-period value is zero or missing.' : `${comparison.changePercent >= 0 ? '+' : ''}${percent(comparison.changePercent)} versus the previous period`}</p><small className="period-formula">Formula: (selected period − previous period) ÷ |previous period| × 100</small></> : <p className="empty-state">This report does not contain two complete matching periods.</p>}</article></section>
      <section className="metric-sku-chart concentration-card"><div className="section-label"><span>Business concentration</span><small>How dependent the business is on a few SKUs</small></div><div className="concentration-grid"><div><span>Sales from top 5 SKUs</span><strong>{percent(result.concentration.topFiveSalesShare)}</strong><i><b style={{ width: `${result.concentration.topFiveSalesShare}%` }} /></i></div><div><span>Positive profit from top 5</span><strong>{percent(result.concentration.topFiveProfitShare)}</strong><i><b style={{ width: `${result.concentration.topFiveProfitShare}%` }} /></i></div></div><div className="concentration-lists">{[{ label: 'SKUs generating 80% of sales', note: 'Fewer SKUs means greater dependency', items: result.concentration.salesContributors }, { label: 'SKUs generating 80% of positive profit', note: 'Loss-making SKUs are excluded', items: result.concentration.profitContributors }].map(list => <details key={list.label}><summary><span><strong>{list.items.length}</strong>{list.label}<small>{list.note}</small></span><b>Show SKUs</b></summary><div>{list.items.map((item, index) => <button key={item.sku} onClick={() => setSku(item.sku)}><b>{index + 1}</b><span><strong title={item.sku}>{item.sku}</strong><small>{percent(item.contributionPercent)} contribution · {percent(item.cumulativePercent)} cumulative</small></span><em>{formatMoney(item.value)}</em></button>)}</div></details>)}</div></section>
      <section className="metric-sku-chart performer-section"><div className="section-label"><span>Top and low performing SKUs</span><small>Ranked by profit · select a SKU to investigate</small></div><div className="performer-columns">{[{ label: 'Top performers', items: result.profitLeaders, className: 'leaders' }, { label: 'Needs attention', items: result.profitLaggards, className: 'laggards' }].map(column => <article className={column.className} key={column.label}><header><strong>{column.label}</strong><small>{column.className === 'leaders' ? 'Highest profit contribution' : 'Lowest profit contribution'}</small></header><div>{column.items.map((item, index) => <button key={item.sku} onClick={() => setSku(item.sku)}><b>{index + 1}</b><span><strong title={item.sku}>{item.sku}</strong><small>Sales {formatMoney(item.grossSales)} · Margin {percent(item.profitMargin)} · Returns {percent(item.returnRate)}</small></span><em className={item.profit < 0 ? 'bad-text' : 'good-text'}>{formatMoney(item.profit)}</em></button>)}</div></article>)}</div></section>
      <section className="metric-sku-chart sku-action-section"><div className="section-label"><span>SKU Action Board</span><small>Every active SKU is placed in one decision group</small></div><p className="action-board-rule">Portfolio benchmarks: strong sales ≥ {formatMoney(result.actionBoard.salesThreshold)} · healthy margin ≥ {percent(result.actionBoard.marginThreshold)} · high-return warning ≥ {percent(result.actionBoard.returnRiskThreshold)}</p><div className="sku-action-board">{result.actionBoard.groups.map(group => <article className={`action-group ${group.id.toLowerCase()}`} key={group.id}><header><div><strong>{group.label}</strong><small>{group.guidance}</small></div><b>{group.items.length}</b></header><div className="action-items">{group.items.length ? group.items.slice(0, 8).map(item => <button key={item.sku} onClick={() => setSku(item.sku)}><div><strong title={item.sku}>{item.sku}</strong><span>{item.reason}</span></div><dl><div><dt>Sales</dt><dd>{formatMoney(item.grossSales)}</dd></div><div><dt>Profit</dt><dd className={item.profit < 0 ? 'bad-text' : 'good-text'}>{formatMoney(item.profit)}</dd></div><div><dt>Margin</dt><dd>{percent(item.profitMargin)}</dd></div><div><dt>Returns</dt><dd>{percent(item.returnRate)}</dd></div><div><dt>RTO</dt><dd>{percent(item.rtoRate)}</dd></div><div><dt>Customer</dt><dd>{percent(item.customerReturnRate)}</dd></div><div><dt>Easy Ship</dt><dd>{formatMoney(item.easyShipFees)}</dd></div><div><dt>Orders</dt><dd>{item.orders}</dd></div></dl><span className="open-sku">View SKU →</span></button>) : <p>No SKUs in this group.</p>}</div></article>)}</div></section>
      <section className="metric-visual-grid"><article className="metric-sku-chart"><div className="section-label"><span>Top movers</span><small>{comparison ? `${comparison.label} versus previous period` : 'No dated comparison'}</small></div><div className="mover-list">{comparison?.movers.map(item => <button key={item.sku} onClick={() => setSku(item.sku)}><span>{item.sku}</span><strong className={item.change < 0 ? 'bad-text' : 'good-text'}>{item.change >= 0 ? '+' : ''}{value(item.change)}</strong></button>)}</div></article><article className="metric-sku-chart"><div className="section-label"><span>Data quality</span><small>Factors affecting interpretation</small></div><div className="quality-list"><span><b>{result.quality.missingCostSkus}</b> SKUs missing cost</span><span><b>{value(result.quality.unassignedAmount)}</b> unassigned</span><span><b>{result.quality.unknownLocationOrders}</b> orders without state</span><span><b>{result.quality.unknownReturnUnits}</b> returns not classified</span></div></article></section>
      <div className="metric-table-head"><div><h3>All SKUs</h3><p>Select a row for the complete SKU overview.</p></div><div className="ranking-controls"><select value={rankDirection} onChange={event => setRankDirection(event.target.value as 'TOP' | 'BOTTOM')}><option value="TOP">Highest first</option><option value="BOTTOM">Lowest first</option></select><label><input type="checkbox" checked={hideZero} onChange={event => setHideZero(event.target.checked)} /> Hide zero</label><label className="metric-search"><span>Find a SKU</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search SKU" /></label></div></div><div className="table-scroll"><table><thead><tr><th>SKU</th><th>{result.label}</th><th>Contribution</th><th>Cumulative</th><th>Gross sales</th><th>Orders</th></tr></thead><tbody>{rows.map(row => <tr key={row.label} className={row.assigned ? 'clickable-order' : 'unassigned-row'} onClick={() => row.sku && setSku(row.sku)}><td><strong>{row.label}</strong>{!row.assigned ? <small>Not reliably attributable to one SKU</small> : null}</td><td className={(row.value ?? 0) < 0 ? 'bad-text' : ''}>{value(row.value)}</td><td>{row.assigned ? percent(row.contributionPercent) : '—'}</td><td>{row.assigned ? percent(row.cumulativePercent) : '—'}</td><td>{row.assigned ? formatMoney(row.grossSales) : '—'}</td><td>{row.assigned ? row.orders.toLocaleString('en-IN') : '—'}</td></tr>)}</tbody></table></div>{!result.additive ? <p className="metric-note">Rates and averages are calculated independently for each SKU; they should not be added together.</p> : null}</div> : <div className="sku-workspace">
      {product.missingCost ? <div className="drilldown-warning">Product cost is missing for this SKU. Profit follows the configured missing-cost policy.</div> : null}
      {workspace ? <SkuCommercialOverview product={product} workspace={workspace} formatMoney={formatMoney} /> : null}
      <SkuGeographyPanel product={product} formatMoney={formatMoney} />
      <SkuOrderInvestigation product={product} previousProduct={previousProduct} formatMoney={formatMoney} />
    </div>}
  </section></div>
}
