import { useState } from 'react'
import type { OrderProfitSummary, SkuProfitSummary } from '../core/analytics/orderProfit'
import { SkuTrendChart } from './SkuTrendChart'

type Props = { orders: readonly OrderProfitSummary[]; skuSummary?: SkuProfitSummary; formatMoney: (value: number) => string; onClose: () => void }

function OrderDetail({ order, formatMoney }: { order: OrderProfitSummary; formatMoney: (value: number) => string }) {
  const components = [['Gross sales', order.grossSales], ['Product refunds', -order.refunds], ['Marketplace charges', -order.marketplaceCharges], ['Net shipping fees', -order.shippingFees], ['Advertising', -order.advertising], ['Reimbursements', order.reimbursements], ['Tax included', order.tax], ['Other operating', order.otherOperating], ['Net COGS', -order.netCogs]] as const
  return <div className="order-detail"><div className="order-detail-title"><div><small>Selected order</small><h3>{order.orderId}</h3><p>{order.skus.join(', ') || 'No SKU'}{order.state ? ` · ${order.state}` : ''}</p>{order.returnType ? <span className={`return-pill ${order.returnType.toLowerCase()}`}>{order.returnType === 'CUSTOMER_RETURN' ? 'Customer return' : order.returnType}</span> : null}</div><strong className={order.profit >= 0 ? 'good-text' : 'bad-text'}>{order.profitReady ? formatMoney(order.profit) : 'Incomplete'}</strong></div>
    {order.missingSkus.length ? <div className="drilldown-warning">Cost missing for {order.missingSkus.join(', ')}. The current ₹0 policy is visibly applied.</div> : null}
    {order.returnEvidence ? <div className="return-evidence">{order.returnEvidence}</div> : null}<div className="profit-components">{components.map(([label, value]) => <div key={label}><span>{label}</span><strong className={value < 0 ? 'bad-text' : value > 0 ? 'good-text' : ''}>{formatMoney(value)}</strong></div>)}</div><div className="profit-total"><span>Profit after ads</span><strong className={order.profit >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(order.profit)}</strong></div>
    <details className="event-audit"><summary>{order.events.length} source-linked financial events</summary><div className="table-scroll"><table><thead><tr><th>Type</th><th>Class</th><th>Raw label</th><th>Amount</th></tr></thead><tbody>{order.events.map((event) => <tr key={event.id}><td>{event.event}</td><td>{event.amountType}</td><td>{event.rawType || event.rawDescription || '—'}</td><td className={event.amount >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(event.amount)}</td></tr>)}</tbody></table></div></details>
  </div>
}

export function OrderProfitDrilldown({ orders, skuSummary, formatMoney, onClose }: Props) {
  const visibleOrders = skuSummary?.orders ?? orders
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const selected = visibleOrders.find((order) => order.orderId === selectedId) ?? null
  const metrics = skuSummary ? [['Gross sales', formatMoney(skuSummary.grossSales), 'positive'], ['Profit', formatMoney(skuSummary.profit), skuSummary.profit >= 0 ? 'positive' : 'negative'], ['Profit margin', `${skuSummary.profitMargin.toFixed(2)}%`, skuSummary.profitMargin >= 0 ? 'positive' : 'negative'], ['Net delivered', skuSummary.netDeliveredQuantity.toLocaleString('en-IN'), 'accent'], ['RTO units', skuSummary.rtoQuantity.toLocaleString('en-IN'), 'negative'], ['Customer returns', skuSummary.customerReturnQuantity.toLocaleString('en-IN'), 'negative'], ['ASP', formatMoney(skuSummary.averageSellingPrice), 'neutral'], ['Net COGS', formatMoney(skuSummary.netCogs), 'negative'], ['Profit / unit', formatMoney(skuSummary.profitPerDeliveredUnit), skuSummary.profitPerDeliveredUnit >= 0 ? 'positive' : 'negative']] as const : []
  const costRows = skuSummary ? [['Marketplace charges', skuSummary.marketplaceCharges, 'fee'], ['Net shipping', skuSummary.shippingFees, 'shipping'], ['Net COGS', skuSummary.netCogs, 'cogs'], ['Reimbursements', skuSummary.reimbursements, 'income']] as const : []
  const maxCost = Math.max(1, ...costRows.map((row) => Math.abs(row[1])))

  return <div className="drilldown-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className={`order-drilldown ${skuSummary ? 'sku-mode' : ''}`} role="dialog" aria-modal="true" aria-label={skuSummary ? 'SKU profitability drilldown' : 'Order profit drilldown'}>
    <header className="drilldown-head"><div><small>{skuSummary ? 'SKU profitability' : 'Profit drilldown'}</small><h2>{skuSummary?.sku ?? 'Order-level profitability'}</h2><p>{visibleOrders.length.toLocaleString('en-IN')} orders in the current dashboard selection</p></div><button className="close" onClick={onClose} aria-label="Close">×</button></header>
    {skuSummary ? <div className="sku-drilldown-content">{skuSummary.missingCost ? <div className="drilldown-warning">This SKU has no saved cost. Profit currently follows the visible missing-cost policy.</div> : null}<div className="sku-metric-grid">{metrics.map(([label, value, tone]) => <article className={`sku-mini-metric ${tone}`} key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
      <div className="sku-visual-grid"><SkuTrendChart data={skuSummary.trend} formatMoney={formatMoney} /><div className="sku-cost-card"><div className="sku-chart-head"><div><small>Unit economics</small><h3>Cost breakdown</h3></div></div>{costRows.map(([label, value, kind]) => <div className={`sku-cost-row ${kind}`} key={label}><span>{label}</span><div><i style={{ width: `${Math.abs(value) / maxCost * 100}%` }} /></div><strong>{formatMoney(value)}</strong></div>)}</div></div>
      <section className="sku-orders"><div className="section-label"><span>Individual orders</span><small>Click an order to audit its profit</small></div><div className="sku-order-table table-scroll"><table><thead><tr><th>Order</th><th>Date</th><th>Gross sales</th><th>Refunds</th><th>Fees + shipping</th><th>COGS</th><th>Profit</th></tr></thead><tbody>{visibleOrders.map((order) => <tr key={order.orderId} className="clickable-order" onClick={() => setSelectedId(order.orderId)}><td><strong>{order.orderId}</strong></td><td>{order.date ?? '—'}</td><td>{formatMoney(order.grossSales)}</td><td>{formatMoney(order.refunds)}</td><td>{formatMoney(order.marketplaceCharges + order.shippingFees)}</td><td>{formatMoney(order.netCogs)}</td><td className={order.profit >= 0 ? 'good-text' : 'bad-text'}>{formatMoney(order.profit)}</td></tr>)}</tbody></table></div></section>
      {selected ? <div className="inline-order-audit"><button className="close inline-close" onClick={() => setSelectedId(null)} aria-label="Close order audit">×</button><OrderDetail order={selected} formatMoney={formatMoney} /></div> : null}</div>
      : <div className="drilldown-layout"><div className="order-list" aria-label="Orders">{!visibleOrders.length ? <div className="empty-state">No orders match this selection.</div> : visibleOrders.map((order) => <button key={order.orderId} className={order.orderId === selected?.orderId ? 'selected' : ''} onClick={() => setSelectedId(order.orderId)}><span><strong>{order.orderId}</strong><small>{order.date ?? 'Unknown date'} · {order.skus.join(', ') || 'No SKU'}</small></span><span className={order.profit >= 0 ? 'good-text' : 'bad-text'}><strong>{order.profitReady ? formatMoney(order.profit) : 'Cost missing'}</strong><small>{order.status ?? 'No status'}</small></span></button>)}</div>{selected ? <OrderDetail order={selected} formatMoney={formatMoney} /> : <div className="order-detail"><div className="empty-state">Select an order to inspect its calculation.</div></div>}</div>}
  </section></div>
}
