import { useMemo, useState } from 'react'
import type { CSSProperties } from 'react'
import type { OrderProfitSummary } from '../core/analytics/orderProfit'
import { buildOrderTimeComparison, type TimeMetric } from '../core/analytics/timeAnalysis'
import '../styles/timeAnalysis.css'

type Props = { readonly title: string; readonly description: string; readonly currentOrders: readonly OrderProfitSummary[]; readonly previousOrders: readonly OrderProfitSummary[]; readonly formatMoney: (value: number) => string }
const metricOptions: readonly { id: TimeMetric; label: string }[] = [{ id: 'ORDERS', label: 'Orders' }, { id: 'UNITS', label: 'Units' }, { id: 'SALES', label: 'Gross sales' }, { id: 'PROFIT', label: 'Profit before ads' }, { id: 'RETURNS', label: 'Returns' }]

export function TimeAnalysisPanel({ title, description, currentOrders, previousOrders, formatMoney }: Props) {
  const [metric, setMetric] = useState<TimeMetric>('ORDERS')
  const result = useMemo(() => buildOrderTimeComparison(currentOrders, previousOrders, metric), [currentOrders, previousOrders, metric])
  const format = (value: number) => metric === 'SALES' || metric === 'PROFIT' ? formatMoney(value) : value.toLocaleString('en-IN')
  const maxWeekday = Math.max(1, ...result.weekdays.flatMap(item => [Math.abs(item.current), Math.abs(item.previous)]))
  const maxHour = Math.max(1, ...result.hours.flatMap(item => [Math.abs(item.current), Math.abs(item.previous)]))
  const maxHeat = Math.max(1, ...result.heatmap.map(item => Math.abs(item.change)))
  const maxWeek = Math.max(1, ...result.weeks.flatMap(item => [Math.abs(item.current), Math.abs(item.previous)]))
  return <section className="time-analysis-panel">
    <div className="section-label"><div><span>{title}</span><small>{description} · Asia/Kolkata</small></div><select value={metric} onChange={event => setMetric(event.target.value as TimeMetric)}>{metricOptions.map(option => <option key={option.id} value={option.id}>{option.label}</option>)}</select></div>
    <div className="time-kpis"><article><span>Current orders</span><strong>{result.current.orders}</strong><small>{result.orderChangePercent === null ? 'No previous baseline' : `${result.orderChangePercent >= 0 ? '+' : ''}${result.orderChangePercent.toFixed(1)}% vs previous`}</small></article><article><span>Peak weekday</span><strong>{result.current.peakWeekday ?? '—'}</strong><small>Previous: {result.previous.peakWeekday ?? '—'}</small></article><article><span>Peak hour</span><strong>{result.current.peakHour ?? '—'}</strong><small>Previous: {result.previous.peakHour ?? '—'}</small></article><article><span>Orders / active day</span><strong>{result.current.averageOrdersPerActiveDay.toFixed(1)}</strong><small>Previous: {result.previous.averageOrdersPerActiveDay.toFixed(1)}</small></article><article><span>Weekend share</span><strong>{result.current.weekendShare.toFixed(1)}%</strong><small>Previous: {result.previous.weekendShare.toFixed(1)}%</small></article></div>
    <div className="time-chart-grid"><article><div className="section-label"><span>Weekday comparison</span><small>Current vs previous equal period</small></div><div className="time-bars">{result.weekdays.map(item => <div key={item.key}><span>{item.label}</span><i><b className="current" style={{ width: `${Math.abs(item.current) / maxWeekday * 100}%` }} /><b className="previous" style={{ width: `${Math.abs(item.previous) / maxWeekday * 100}%` }} /></i><strong>{format(item.current)}</strong></div>)}</div></article><article><div className="section-label"><span>Hourly profile</span><small>Current solid · previous outline</small></div><div className="hour-chart">{result.hours.map(item => <div key={item.key} title={`${item.label}: current ${format(item.current)}, previous ${format(item.previous)}`}><i style={{ height: `${Math.abs(item.current) / maxHour * 100}%` }} /><b style={{ height: `${Math.abs(item.previous) / maxHour * 100}%` }} /><small>{Number(item.key) % 3 === 0 ? item.label.slice(0, 2) : ''}</small></div>)}</div></article></div>
    <article className="time-heat-card"><div className="section-label"><span>Weekday × hour change</span><small>Green improved · red declined</small></div><div className="time-heat-scroll"><div className="time-heatmap"><span className="heat-corner" />{Array.from({ length: 24 }, (_, hour) => <small key={hour}>{hour % 3 === 0 ? hour : ''}</small>)}{Array.from({ length: 7 }, (_, weekday) => [<strong key={`day-${weekday}`}>{result.heatmap.find(cell => cell.weekday === weekday)?.weekdayLabel.slice(0, 3)}</strong>, ...result.heatmap.filter(cell => cell.weekday === weekday).map(cell => <div key={`${cell.weekday}-${cell.hour}`} className={cell.change > 0 ? 'up' : cell.change < 0 ? 'down' : ''} style={{ '--strength': Math.max(.08, Math.abs(cell.change) / maxHeat) } as CSSProperties} title={`${cell.weekdayLabel} ${String(cell.hour).padStart(2, '0')}:00 · current ${format(cell.current)} · previous ${format(cell.previous)} · change ${format(cell.change)}`} />)])}</div></div></article>
    <article className="weekly-time-card"><div className="section-label"><span>Weekly activity</span><small>{metricOptions.find(item => item.id === metric)?.label}</small></div><div className="weekly-time-bars">{result.weeks.map(item => <div key={item.key} title={`${item.label}: current ${format(item.current)}, previous ${format(item.previous)}`}><span>{item.label}</span><i><b style={{ width: `${Math.abs(item.current) / maxWeek * 100}%` }} /></i><strong>{format(item.current)}</strong></div>)}</div></article>
    {result.unknownCurrent || result.unknownPrevious ? <p className="metric-note">{result.unknownCurrent} current and {result.unknownPrevious} previous sale orders have unusable timestamps and remain visible in order detail.</p> : null}
  </section>
}
